#!/bin/bash

INSTALL_DIR="/home/$USER/.hod"
FILE_NAME="HOD_Login1.jnlp"
DOWNLOAD_URL="http://www.hodv11.cfwb.be/"$FILE_NAME

# Install if necessary

if [[ ! -e "$INSTALL_DIR" ]]; then
    mkdir -p "$INSTALL_DIR" && echo "Install dir created"
elif [[ ! -d $dir ]]; then
    echo "$INSTALL_DIR already exists but is not a directory" &> /dev/null
fi

cd "$INSTALL_DIR"
if [[ ! -f "$FILE_NAME" ]]; then
    if [ "$(expr substr "$(uname)")" == "Darwin" ]; then
        curl -O "$DOWNLOAD_URL" &> /dev/null && echo "Download OK"      
    elif [ "$(expr substr "$(r "$(uname -s)" 1 5))")" ]; then
        wget --continue --no-clobber "$DOWNLOAD_URL" &> /dev/null && echo "Download OK"
    fi
fi



# Launch

echo "Launching!"
cp -r "$INSTALL_DIR"/HOD* ~
javaws "$FILE_NAME" &> /dev/null



# Clean

sleep 10
running_pid=$(pgrep -f "HOD")

while kill -0 "$running_pid" 2> /dev/null; do
    echo "Waiting for process end..."
    sleep 30
done

echo "Cleaning"
cd ~
mv -f connection.test www.hodv11.* HOD* "$INSTALL_DIR" &> /dev/null
rm -r connection.test www.hodv11.* HOD* &> /dev/null
